# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = FactoryAutoTest
DESTDIR = ./x64/Debug_UI
CONFIG += debug
DEFINES += UI_DEBUG
LIBS += -l/"$(INHERIT)/" \
    -l$(Qt_LIBS_) \
    -ltkVISA64
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug_ui
UI_DIR += .
RCC_DIR += .
include(FactoryAutoTest.pri)
win32:RC_FILE = FactoryAutoTest.rc
